# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=400)),
                ('sent', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('sent',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, max_length=200, verbose_name='полное имя')),
                ('postcode', models.CharField(max_length=20, verbose_name='индекс')),
                ('address', models.TextField(max_length=500, verbose_name='адрес')),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='последний визит')),
                ('gift_sent', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='подарок отправлен')),
                ('gift_received', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='подарок получен')),
                ('giftee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='santa', to='clubadm.Member', verbose_name='получатель подарка')),
            ],
            options={
                'verbose_name': 'участник',
                'ordering': ('season', 'fullname'),
                'verbose_name_plural': 'участники',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_oldfag', models.BooleanField(default=False, help_text='Отметьте, чтобы снять ограничение кармы.', verbose_name='старый участник')),
                ('access_token', models.CharField(blank=True, help_text='Токен для доступа к API Хабрахабра/Geektimes.', max_length=40, verbose_name='токен доступа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(default=2015, primary_key=True, serialize=False, verbose_name='год')),
                ('gallery', models.URLField(blank=True, verbose_name='пост хвастовства подарками')),
                ('signups_start', models.DateField(verbose_name='начало регистрации')),
                ('signups_end', models.DateField(verbose_name='жеребьевка адресов')),
                ('ship_by', models.DateField(help_text='После этой даты сезон закрывается и уходит в архив.', verbose_name='последний срок отправки подарка')),
            ],
            options={
                'get_latest_by': 'year',
                'verbose_name': 'сезон',
                'ordering': ('year',),
                'verbose_name_plural': 'сезоны',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubadm.Season', verbose_name='сезон'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='mail',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clubadm.Member'),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clubadm.Member'),
        ),
    ]
